FROM amazonlinux
WORKDIR /google-chrome

RUN yum -y install wget && \
    yum -y install tar && \
    yum -y install gzip && \
    yum -y install unzip
    
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm && \
    yum -y install google-chrome-stable_current_x86_64.rpm

WORKDIR /chrome-driver

RUN wget https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip

ENV PATH /chrome-driver:$PATH

WORKDIR /framework

RUN rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm && \
    yum -y install dotnet-sdk-3.1

WORKDIR /pickaxe-dev

RUN wget https://github.com/bitsummation/pickaxe/archive/CoreWithCodeDom.zip && \
    unzip CoreWithCodeDom.zip  && \
    rm CoreWithCodeDom.zip 

WORKDIR /