//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Pickaxe.Runtime;
using Pickaxe.Runtime.Dom;
using System;
using System.Collections.Generic;
using System.Linq;



public class Code : RuntimeBase
{

    private Scope_8d019e5279b0408883b00b14fb99d73c _Scope_8d019e5279b0408883b00b14fb99d73c;

    private Scope_8c38e2c124234afdbfa1f73ec9a9d6ae _Scope_8c38e2c124234afdbfa1f73ec9a9d6ae;

    public Code(string[] args) :
        base(args)
    {
        _Scope_8d019e5279b0408883b00b14fb99d73c = new Scope_8d019e5279b0408883b00b14fb99d73c();
        _Scope_8c38e2c124234afdbfa1f73ec9a9d6ae = new Scope_8c38e2c124234afdbfa1f73ec9a9d6ae();
        TotalOperations = (TotalOperations + 1);
    }

    public void Run()
    {
        InitProxies();
        Block_b8bb721767d543088598a63f4cbf482a();
        Step_7238b80f626845068c83798551258777();
    }

    public void Block_b8bb721767d543088598a63f4cbf482a()
    {
        Step_60daf8877e5d4916b14c43b4d09ec7b3();
    }

    private CodeTable<anon_8d75862905964bbc8742d2edd9a6dee6> From_3e580952451a484e8ddaf7e9f5b812f4()
    {
        Call(4);
        IEnumerable<anon_009d44e0fefa440c8f977a94b19c5d85> join = Fetch_103d3bc14ca748e29fd4934b65ba11a9();
        return Join_c96db8efc994414c8d6558ea2ee03bfc(join);
    }

    private CodeTable<anon_05aedd4d330f4920812021e15d20d5cc> From_ef409edfbf0149978c01ae843e989fa0()
    {
        Call(8);
        IEnumerable<anon_05aedd4d330f4920812021e15d20d5cc> join = Fetch_e2c2c45887c240a39fd29c62569bf48d();
        CodeTable<anon_05aedd4d330f4920812021e15d20d5cc> newTable = new CodeTable<anon_05aedd4d330f4920812021e15d20d5cc>();
        newTable.SetRows(join.ToList());
        return newTable;
    }

    private RuntimeTable<DownloadPage> Download_b41c2e4f4cfd499c8b1249254321500d()
    {
        Call(8);
        return new SelectDownloadTable(Pickaxe.Runtime.LazyDownloadArgs.CreateWebRequestArgs(this, 8, 1, "http://mock.com"));
    }

    private IEnumerable<anon_05aedd4d330f4920812021e15d20d5cc> Fetch_e2c2c45887c240a39fd29c62569bf48d()
    {
        RuntimeTable<DownloadPage> table = Download_b41c2e4f4cfd499c8b1249254321500d();
        return table.Select(o =>
        {
            return Copy_6b26f45a97fd4780a386e1da045f43c3(o);
        });
    }

    private anon_05aedd4d330f4920812021e15d20d5cc Copy_6b26f45a97fd4780a386e1da045f43c3(DownloadPage o)
    {
        anon_05aedd4d330f4920812021e15d20d5cc t = new anon_05aedd4d330f4920812021e15d20d5cc();
        t.DownloadPage = o;
        return t;
    }

    private CodeTable<t> Nested_Select_69874fb93a394346856bf38c9505effe()
    {
        Call(6);
        CodeTable<t> result = new BufferTable<t>();
        CodeTable<anon_05aedd4d330f4920812021e15d20d5cc> fromTable = From_ef409edfbf0149978c01ae843e989fa0();
        fromTable = Where_2fc455310b30431b94bd1307b8656564(fromTable);
        IEnumerator<anon_05aedd4d330f4920812021e15d20d5cc> x = fromTable.GetEnumerator();
        for (
        ; x.MoveNext();
        )
        {
            anon_05aedd4d330f4920812021e15d20d5cc row = x.Current;
            IEnumerator<HtmlElement> y = row.DownloadPage.nodes.GetEnumerator();
            for (
            ; y.MoveNext();
            )
            {
                HtmlElement node = y.Current;
                t resultRow = new t();
                resultRow.k = 1;
                resultRow.p = node.Pick("li:nth-of-type(2)").TakeText();
                result.Add(resultRow);
            }
            row.DownloadPage.Clear();
        }
        return result;
    }

    private CodeTable<anon_05aedd4d330f4920812021e15d20d5cc> Where_2fc455310b30431b94bd1307b8656564(CodeTable<anon_05aedd4d330f4920812021e15d20d5cc> table)
    {
        Call(9);
        CodeTable<anon_05aedd4d330f4920812021e15d20d5cc> newTable = new CodeTable<anon_05aedd4d330f4920812021e15d20d5cc>();
        IList<anon_05aedd4d330f4920812021e15d20d5cc> rows = table.Where(row =>
        {
            return row.DownloadPage.CssWhere(ref row.DownloadPage, "#match-tests");
        }).ToList();
        newTable.SetRows(rows);
        return newTable;
    }

    private IEnumerable<anon_009d44e0fefa440c8f977a94b19c5d85> Fetch_103d3bc14ca748e29fd4934b65ba11a9()
    {
        CodeTable<t> table = Nested_Select_69874fb93a394346856bf38c9505effe();
        return table.Select(o =>
        {
            return Copy_5faa9f7bdf354bc390acceea48f7f1c3(o);
        });
    }

    private anon_009d44e0fefa440c8f977a94b19c5d85 Copy_5faa9f7bdf354bc390acceea48f7f1c3(t o)
    {
        anon_009d44e0fefa440c8f977a94b19c5d85 t = new anon_009d44e0fefa440c8f977a94b19c5d85();
        t.t = o;
        return t;
    }

    private CodeTable<anon_8d75862905964bbc8742d2edd9a6dee6> Join_c96db8efc994414c8d6558ea2ee03bfc(IEnumerable<anon_009d44e0fefa440c8f977a94b19c5d85> outer)
    {
        Call(13);
        IEnumerable<anon_89b97c9b9fdc4fea82f907177168f538> table = Fetch_872dc95e7ccf4e188757e4e5b5bde9da();
        IList<anon_8d75862905964bbc8742d2edd9a6dee6> join = new List<anon_8d75862905964bbc8742d2edd9a6dee6>();
        IEnumerator<anon_009d44e0fefa440c8f977a94b19c5d85> o = outer.GetEnumerator();
        for (
        ; o.MoveNext();
        )
        {
            anon_009d44e0fefa440c8f977a94b19c5d85 oc = o.Current;
            IEnumerator<anon_89b97c9b9fdc4fea82f907177168f538> i = table.GetEnumerator();
            for (
            ; i.MoveNext();
            )
            {
                anon_89b97c9b9fdc4fea82f907177168f538 ic = i.Current;
                if ((ic.p.k == oc.t.k))
                {
                    anon_8d75862905964bbc8742d2edd9a6dee6 t = new anon_8d75862905964bbc8742d2edd9a6dee6();
                    t.t = oc.t;
                    t.p = ic.p;
                    join.Add(t);
                }
            }
        }
        CodeTable<anon_8d75862905964bbc8742d2edd9a6dee6> newTable = new CodeTable<anon_8d75862905964bbc8742d2edd9a6dee6>();
        newTable.SetRows(join.ToList());
        return newTable;
    }

    private CodeTable<p> Nested_Select_8a17427c327a49a3a772c9e9ec0c5282()
    {
        Call(13);
        CodeTable<p> result = new BufferTable<p>();
        p resultRow = new p();
        resultRow.k = 1;
        result.Add(resultRow);
        return result;
    }

    private IEnumerable<anon_89b97c9b9fdc4fea82f907177168f538> Fetch_872dc95e7ccf4e188757e4e5b5bde9da()
    {
        CodeTable<p> table = Nested_Select_8a17427c327a49a3a772c9e9ec0c5282();
        return table.Select(o =>
        {
            return Copy_b7fd5321112a4b0591446b87df2afc34(o);
        });
    }

    private anon_89b97c9b9fdc4fea82f907177168f538 Copy_b7fd5321112a4b0591446b87df2afc34(p o)
    {
        anon_89b97c9b9fdc4fea82f907177168f538 t = new anon_89b97c9b9fdc4fea82f907177168f538();
        t.p = o;
        return t;
    }

    private Table<ResultRow> Select_357ad44759424a42a8c316d4b3d2bd70()
    {
        Call(3);
        RuntimeTable<ResultRow> result = new RuntimeTable<ResultRow>();
        result.AddColumn("p");
        result.AddColumn("k");
        CodeTable<anon_8d75862905964bbc8742d2edd9a6dee6> fromTable = From_3e580952451a484e8ddaf7e9f5b812f4();
        IEnumerator<anon_8d75862905964bbc8742d2edd9a6dee6> x = fromTable.GetEnumerator();
        for (
        ; x.MoveNext();
        )
        {
            anon_8d75862905964bbc8742d2edd9a6dee6 row = x.Current;
            ResultRow resultRow = new ResultRow(2);
            resultRow[0] = row.t.p;
            resultRow[1] = row.p.k;
            result.Add(resultRow);
        }
        OnSelect(result);
        return result;
    }

    public void Step_60daf8877e5d4916b14c43b4d09ec7b3()
    {
        Select_357ad44759424a42a8c316d4b3d2bd70();
        OnProgress();
    }

    public void Step_7238b80f626845068c83798551258777()
    {
        OnProgress(new ProgressArgs(TotalOperations, TotalOperations));
    }

    private class Scope_8d019e5279b0408883b00b14fb99d73c
    {

        public int g_identity;

        public Scope_8d019e5279b0408883b00b14fb99d73c()
        {
        }
    }

    private class Scope_8c38e2c124234afdbfa1f73ec9a9d6ae
    {

        public Scope_8c38e2c124234afdbfa1f73ec9a9d6ae()
        {
        }
    }

    private class anon_05aedd4d330f4920812021e15d20d5cc : IRow
    {

        public DownloadPage DownloadPage;
    }

    private class t : IRow
    {

        public System.Nullable<int> k;

        public string p;
    }

    private class anon_009d44e0fefa440c8f977a94b19c5d85 : IRow
    {

        public t t;
    }

    private class p : IRow
    {

        public System.Nullable<int> k;
    }

    private class anon_89b97c9b9fdc4fea82f907177168f538 : IRow
    {

        public p p;
    }

    private class anon_8d75862905964bbc8742d2edd9a6dee6 : IRow
    {

        public t t;

        public p p;
    }
}
